# Generated by Django 4.2.2 on 2023-06-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('precision', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('clasificacion', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('precision', models.FloatField()),
            ],
        ),
    ]
